# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle (cache)
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - name: Build multi-module (NeoForge excluded)
      run: |
        ./gradlew -PincludeNeo=false --no-daemon --stacktrace \
          :Multiworld-Common:build \
          :Multiworld-Fabric-1.20.1:build \
          :Multiworld-Fabric-1.20.4:build \
          :Multiworld-Fabric-1.20.6:build \
          :Multiworld-Fabric-1.21.1:build \
          :Multiworld-Fabric-1.21.4:build \
          :Multiworld-Fabric-1.21.5:build \
          :Multiworld-Fabric-1.21.9:build \
          :Multiworld-Fabric-bundle:build \
          :Multiworld-Forge-1.20.1:build \
          -x test
    - name: Prepare artifact folder with index
      run: |
        mkdir -p ci-artifacts
        # Prefer root output jars
        if [ -d output ]; then
          find output -maxdepth 1 -type f -name '*.jar' -exec cp {} ci-artifacts/ \;
        fi
        # Also copy per-module libs
        find . -path '*/build/libs/*.jar' \
          -not -name '*-sources.jar' \
          -not -name '*-javadoc.jar' \
          -exec cp {} ci-artifacts/ \;
        # Generate index.txt for clarity
        (echo "Built JARs:"; ls -1 ci-artifacts/*.jar | sed 's#^./##') | tee ci-artifacts/index.txt
    - name: Upload jars (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: multiworld-jars-${{ github.sha }}
        path: |
          ci-artifacts/*
        if-no-files-found: error
        retention-days: 14
